controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_action_controller:
      type: position_controllers/GripperActionController
      
# Configuration for the Arm Controller
arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    allow_nonzero_velocity_at_trajectory_end: true
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

    gains:
      shoulder_pan_joint:      { p: 100.0, i: 0.01, d: 0.1 }
      shoulder_lift_joint:     { p: 100.0, i: 0.01, d: 0.1 }
      elbow_joint:             { p: 100.0, i: 0.01, d: 0.1 }
      wrist_1_joint:           { p: 50.0,  i: 0.01, d: 0.1 }
      wrist_2_joint:           { p: 50.0,  i: 0.01, d: 0.1 }
      wrist_3_joint:           { p: 50.0,  i: 0.01, d: 0.1 }


# Configuration for the Gripper Controller
gripper_action_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
