
joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 20.0          
    has_deceleration_limits: true
    max_deceleration: -20.0         
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position:  3.1415926535897931
    max_velocity: 3.14               
    min_position: -3.1415926535897931
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 20.0        
    has_deceleration_limits: true
    max_deceleration: -20.0       
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position:  3.1415926535897931
    max_velocity: 3.14              
    min_position: -3.1415926535897931
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 20.0          
    has_deceleration_limits: true
    max_deceleration: -20.0         
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position:  3.1415926535897931
    max_velocity: 3.14               
    min_position: -3.1415926535897931
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 20.0        
    has_deceleration_limits: true
    max_deceleration: -20.0       
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position:  3.1415926535897931
    max_velocity: 6.28               
    min_position: -3.1415926535897931
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 20.0        
    has_deceleration_limits: true
    max_deceleration: -20.0       
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position:  3.1415926535897931
    max_velocity: 6.28               
    min_position: -3.1415926535897931
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 20.0         
    has_deceleration_limits: true
    max_deceleration: -20.0         
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position:  3.1415926535897931
    max_velocity: 6.28               
    min_position: -3.1415926535897931


  # Robotiq Gripper Limits 
  robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 1.5             
    has_acceleration_limits: true
    max_acceleration: 5.0          
    has_deceleration_limits: true  
    max_deceleration: -5.0         
